<?php

/*------------------------------------------------------------------

TABLE OF CONTENTS

- Add Home to nav menus
- Default nav menus
- Gae image thumbnail
  -- Alternative image thumbnail
- Ignore Sticky Post
- Post Exceprt Reformat
  -- Reduce Exceprt Word's Lenght
  -- Create "Read More" link for excerpts
  -- Replace appended to autogenerated excerpts
  -- Add "Read More" link to custom excerpt
- Gae grid mode
- Gae search form
- Gae author info
- Gae WP Title
- Gae theme breadcrumbs
- Gae theme pagination
- Gae theme slides
  -- Scripts to support slides
- Gae theme captions
- Gae entry title
- Gae entry pages
- Gae entry categories
- Gae entry tags
- Gae theme copyright
- Gae theme generator
- Gae social_network
- Gae WP title
  -- Replace SEO parameter
  -- Replace SEO paremeter - blogname
- Add body classes
- Gae Entries display
- Gae RSS Feed
- Gae Twitter Feed
	-- Replace tweets content
	-- Replace tweets time
- Gae Flickr Feed
- Gae Video display

------------------------------------------------------------------*/




/*------------------------------------------------------------------
	- Add Home to nav menus
------------------------------------------------------------------*/

function add_home_menu($items, $args) {
	if ( is_front_page() ) {
		$classes = 'menu-item menu-item-0 current-menu-item'; 
	} else {
		$classes = 'menu-item menu-item-0';
	}
	
	if ( ( get_theme_option('home_link', 'top_menu') == 1 && $args->theme_location == 'top_menu' ) || 
		( get_theme_option('home_link', 'main_menu') == 1 && $args->theme_location == 'main_menu' ) ||
		( get_theme_option('home_link', 'bottom_menu') == 1 && $args->theme_location == 'bottom_menu' ) ) {
			$homeItem = '<li class="'. $classes .'">'. $args->before .'<a href="'. get_bloginfo( 'url' ) .'" title="'. __('Home', 'gaetheme') .'">'. $args->link_before . __('Home', 'gaetheme') . $args->link_after .'</a>'. $args->after .'</li>'. "\n";
		} else {
			$homeItem = '';
		}
	return $homeItem . $items;
}
add_filter('wp_nav_menu_items','add_home_menu', 10, 2);





/*------------------------------------------------------------------
	- Default nav menus
------------------------------------------------------------------*/

function gae_nav_menu($args = '') {
	$defaults = array(
		'theme_location' => '', 'container' => true, 'container_class' => '', 'container_id' => '', 'menu_id' => '', 'menu_class' => 'menu', 'callback' => 'pages',
		'depth' => 0, 'child_of' => 0, 'exclude' => '', 'echo' => 1
	);
	$set = wp_parse_args($args, $defaults);
	extract($set, EXTR_SKIP);
	$add_arg['depth'] = preg_replace('/[^0-9,]/', '', $set['depth']);
	$add_arg['child_of'] = preg_replace('/[^0-9,]/', '', $set['child_of']);
	$add_arg['exclude'] = preg_replace('/[^0-9,]/', '', $set['exclude']);
	$call_arg = array_merge( array( 'title_li' => '', 'echo' => 0 ), $add_arg );
	$output = '<ul'. ( isset($set['menu_id']) ? ' id="'. esc_attr($set['menu_id']) .'"' : '' ) . ( isset($set['menu_class']) ? ' class="'. esc_attr($set['menu_class']) .'"' : '' ) .'>'. "\n";
	if ( $set['theme_location'] && get_theme_option('home_link', $set['theme_location']) != '' ) {
		$classes = ($set['callback'] == 'categories') ? 'cat-item cat-item-0' : 'page_item page-item-0';
		if ( is_front_page() || is_home() )
			$classes .= ($set['callback'] == 'categories') ? ' current-cat' : ' current_page_item';
		$output .= '<li class="'. $classes .'"><a href="'. get_bloginfo( 'url' ) .'" title="'. __('Home', 'gaetheme') .'">'. __('Home', 'gaetheme') .'</a></li>'. "\n";
	}
	$output .= ( $set['callback'] == 'categories' ) ? wp_list_categories($call_arg) : wp_list_pages($call_arg);
	$output .= '</ul>'. "\n";
	
	$display = '';
	if ( $set['container'] )
		$display .= '<div'.($set['container_class'] ? ' class="' . esc_attr($set['container_class']) . '"' : '') . ($set['container_id'] ? ' id="' . esc_attr($set['container_id']) . '"' : '') .'>'. $output .'</div>';
	else
		$display .= $output;
		
	if ( $set['echo'] )
		echo $display;
	else
		return $display;
}




/*------------------------------------------------------------------
	- Gae image thumbnail
------------------------------------------------------------------*/

function gae_the_post_thumbnail($post_id=null, $size='post-thumbnail', $attr='') {
	global $_wp_additional_image_sizes;
	$img_size = $_wp_additional_image_sizes[$size];
	$img_crop = ($img_size['crop']) ? '1' : '0';
	$post_id = ( null === $post_id ) ? get_the_ID() : $post_id;
	$defaults = array('class' => 'attachment-'. $size, 'alt' => get_the_title($post_id), 'title' => get_the_title($post_id));
	$set = wp_parse_args($attr, $defaults);
	extract($set, EXTR_SKIP);
	if ( has_post_thumbnail($post_id) ) : 
		$thumb = get_the_post_thumbnail($post_id, $size, array('class' => $set['class'], 'alt' => $set['alt'], 'title' => $set['title']));
	else :
		$thumb = '<img src="'. gae_alt_post_thumb($post_id, $img_size['width'], $img_size['height'], $img_crop) .'" title="'. $set['title'] .'" alt="'. $set['alt'] .'" class="'. $set['class'] .' wp-alt-image" width="'. $img_size['width'] .'" height="'. $img_size['height'] .'" />';
	endif;
	return $thumb;
}


/*	-- Alternative image thumbnail
------------------------------------------------------------------*/

require_once( get_theme_dir('includes') . '/aq_resizer.php' );
function gae_alt_post_thumb($post_id=null, $width='100', $height='100', $crop='1') {
	$post_id = ( null === $post_id ) ? get_the_ID() : $post_id;
	$post = get_post($post_id);
	$post_img = get_children("post_parent=$post_id&post_type=attachment&post_mime_type=image");
	$find_img = preg_match_all('/<img.+src=[\'"]([^\'"]+)[\'"].*>/i', $post->post_content, $matches);
	$crop = ( $crop == 1 ) ? true : false;
	if($post_img) {
		$ids = array_reverse(array_keys($post_img));
		$img_url = aq_resize( wp_get_attachment_url($ids[0]), $width, $height, $crop );
	} elseif ($matches[1]) {
		$img_url = get_theme_uri('includes') .'/timthumb.php?src='. $matches[1][0] .'&amp;w='. $width .'&amp;h='. $height .'&amp;zc='. $crop .'&amp;q=85';
	} else {
		$par = explode(get_bloginfo('wpurl'), get_theme_uri() .'/images/blank_thumb.gif');
		$img_url = get_theme_uri('includes') .'/timthumb.php?src='. $par[1] .'&amp;w='. $width .'&amp;h='. $height .'&amp;zc='. $crop .'&amp;q=85';
	}
	return $img_url;
}




/*------------------------------------------------------------------
	- Ignore Sticky Post
------------------------------------------------------------------*/

function gae_ignore_sticky( $query ) {
	$query->query_vars['ignore_sticky_posts'] = 1;
	return;
}
add_action('pre_get_posts', 'gae_ignore_sticky', 1);

/*------------------------------------------------------------------
	- Post Exceprt Reformat
------------------------------------------------------------------*/

/*	-- Reduce Exceprt Word's Lenght
------------------------------------------------------------------*/

function gae_reduce_excerpt() {
	if ( get_theme_option('post_excerpt_length') != '0' ) {
		return get_theme_option('post_excerpt_length');
	} else {
		return 55;
	}
}
add_filter('excerpt_length', 'gae_reduce_excerpt'); 


/*	-- Create "Read More" link for excerpts
------------------------------------------------------------------*/

function gae_post_more() {
	if ( get_theme_option('read_more') != '' ) {
		$content	= ' <a class="entry-more" href="'. get_permalink() . '">'. get_theme_option('read_more') .'</a>'. "\n";
	} else {
		$content	= '';
	}
	return $content;
}


/*	-- Replace "[...]" and add "Read More" link
------------------------------------------------------------------*/

function gae_excerpt_more( $more ) {
	return ' &hellip;' . gae_post_more();
}
add_filter( 'excerpt_more', 'gae_excerpt_more' );



/*	-- Add "Read More" link to custom excerpts
------------------------------------------------------------------*/

function gae_custom_excerpt_more( $output ) {
	if ( has_excerpt() && ! is_attachment() ) {
		$output .= gae_post_more();
	}
	return $output;
}
add_filter( 'get_the_excerpt', 'gae_custom_excerpt_more' );




/*------------------------------------------------------------------
	- Gae author info
------------------------------------------------------------------*/

function gae_entry_author_info($avatar_size='64') {
	global $post;
	$avatar_size	= ( $avatar_size < 16 || $avatar_size > 80 ) ? '64' : absint($avatar_size);
	$author_id		= $post->post_author;
	$author_name	= get_the_author_meta('display_name', $author_id);
	$author_desc	= get_the_author_meta('description', $author_id);
	
	if (get_theme_option('author_info_enable') == 'true') {
	?><div class="entry-author clearfix">
		<?php echo get_avatar( $author_id, $avatar_size ); ?>
		<div class="author-info">
			<h4 class="author-name"><?php printf( __( 'About %s', 'gaetheme' ), $author_name ); ?></h4>
			<p><?php echo $author_desc . '&nbsp;'; ?></p>			
			<div class="author-link">
				<a href="<?php echo get_author_posts_url( $author_id ); ?>">
					<?php printf( __( 'View all posts by %s', 'gaetheme' ), $author_name .' &raquo;' ); ?>
				</a>
			</div>
		</div>
	</div><?php 
	}
}




/*------------------------------------------------------------------
	- Gae WP Title
------------------------------------------------------------------*/

function new_wp_title() {
	do_action('new_wp_title');
}


function gae_new_title() {
	global $page, $paged;
	if (function_exists('gae_wp_title')) { echo gae_wp_title(); }
	else {
		wp_title( '|', true, 'right' );
		bloginfo( 'name' );
		if ( ( is_home() || is_front_page() ) && get_bloginfo('description') )
			echo ' | '. get_bloginfo('description');
	}
}
add_filter('new_wp_title','gae_new_title');




/*------------------------------------------------------------------
	- Gae grid mode
------------------------------------------------------------------*/

function gae_html_grid_mode($default='list') {
	$html 	= '<div class="switcher">'
			. '<span class="grid'. ( ($default=='grid') ? ' on' : '' ) .'" title="'. __('Two Columns', 'gaetheme') .'">'. __('Grid', 'gaetheme') .'</span>'
			. '<span class="list'. ( ($default=='list') ? ' on' : '' ) .'" title="'. __('One Column', 'gaetheme') .'">'. __('List', 'gaetheme') .'</span>'
			. '</div>';
	return $html;
}



/*------------------------------------------------------------------
	- Gae search form
------------------------------------------------------------------*/

function gae_search_form($class='clearfix',$id='search-form') {
	$search_text = get_theme_option('search_text') ? get_theme_option('search_text') : '';
?><div class="<?php echo esc_attr($class); ?>">
	<form method="get" id="<?php echo esc_attr($id); ?>" action="<?php bloginfo('url'); ?>">
		<input class="s" type="text" name="s" value="<?php echo $search_text; ?>" onfocus="if (this.value == '<?php echo $search_text; ?>') {this.value = '';}" onblur="if (this.value == '') {this.value = '<?php echo $search_text; ?>';}" />
		<input type="image" src="<?php echo get_theme_uri('images'); ?>/search.png" alt="" class="submit" name="submit" />
	</form>
</div><?php
}




/*------------------------------------------------------------------
	- Gae theme breadcrumbs
------------------------------------------------------------------*/

function the_breadcrumbs() {
	if (function_exists('gae_theme_breadcrumbs')) return gae_theme_breadcrumbs();
}




/*------------------------------------------------------------------
	- Gae theme pagination
------------------------------------------------------------------*/

function get_pagination() {
	global $wp_query;
	if ($wp_query->max_num_pages < 2) return;
	echo '<div class="navigation clearfix">'. "\n";
	if (get_theme_option('pagination_style') == 'nav_paging' && function_exists('gae_pagination')) echo gae_pagination('2');
	else gae_wp_pagination();
	echo '</div>' . "\n";
}


function gae_wp_pagination() {
	?><div class="nav-pages">
		<span class="nav-prev"><?php previous_posts_link( '&laquo; '. __('Previous Entries', 'gaetheme') ); ?></span>
		<span class="nav-next"><?php next_posts_link( __('Next Entries', 'gaetheme') .' &raquo;' ); ?></span>
	</div><?php
}


function gae_entry_pagination() {
	global $post;
?><div class="navigation clearfix">
	<div class="nav-pages">
		<span class="nav-prev"><?php previous_post_link('%link', '&laquo; '. __('Previous Post', 'gaetheme')); ?></span>
		<span class="nav-next"><?php next_post_link('%link',  __('Next Post', 'gaetheme') .' &raquo;' ); ?></span>
	</div>
</div><?php
}


/*------------------------------------------------------------------
	- Gae theme slides
------------------------------------------------------------------*/

function the_slides() {
	if (function_exists('gae_theme_slides')) return gae_theme_slides();
	else
		if (is_home())
			get_template_part( 'sliders' );
			add_action( 'wp_footer', 'gae_scripts_slides' );
}


/*------------------------------------------------------------------
	-- Scripts to support slides
------------------------------------------------------------------*/

function gae_scripts_slides() {
	$efect = get_theme_option('slide_effect');
	$hover = ( get_theme_option('slide_hover') == 'true' ) ? 'true' : 'false';
	$speed = ( get_theme_option('slide_speed') < 1000 || get_theme_option('slide_speed') > 10000 ) ? '6000' : get_theme_option('slide_speed');
	$pause = ( get_theme_option('slide_pause') < 100 || get_theme_option('slide_pause') > 1000 ) ? '350' : get_theme_option('slide_pause');
	?><script type="text/javascript">
	$(document).ready(function($) { $('#featured .slides').carouFredSel({ scroll: { fx: '<?php echo $efect;?>', duration: <?php echo $pause;?>, pauseOnHover: <?php echo $hover;?> }, auto: <?php echo $speed;?>, items: { visible: 1 }, prev: '.prev', next: '.next', pagination: '.pagination', responsive  : true, width: '100%' }); });
	</script><?php
}



/*------------------------------------------------------------------
	- Gae theme captions
------------------------------------------------------------------*/

function gae_theme_caption() {
	global $authordata, $paged, $s;
	$allsearch = new WP_Query("s=$s");
	$searchcount  = $allsearch->post_count;
	$object = get_queried_object();
	
	if (is_singular()) return;
	if (is_home() && $paged < 2) {
		$capt	= '<h1>'. __('Latest Entries', 'gaetheme') .'</h1>';
		$desc	= '';
	} 
	elseif (is_category()) {
		$capt	= '<h1>'. single_cat_title('', false) .'</h1>';
		$desc	= category_description() ? category_description() : '';
	} 
	elseif (is_tag()) {
		$capt	= '<h1>'. single_tag_title('', false) .'</h1>';
		$desc	= tag_description() ? tag_description() : '';
	} 
	elseif (is_tax()) {
		$capt	= '<h1>'. single_term_title('', false) .'</h1>';
		$desc	= term_description( $object->term_id, $object->name ) ? term_description( $object->term_id, $object->name ) : '';
	} 
	elseif (is_post_type_archive()) {
		$capt	= '<h1>'. post_type_archive_title('',false) .'</h1>';
		$desc	= '';
	} 
	elseif (is_author()) {
		$capt	= '<h1>'. sprintf( __('Archives: %s', 'gaetheme'),  $object->display_name ) .'</h1>';
		$desc	= get_the_author_meta('description', $object->ID) ? get_the_author_meta('description', $object->ID) : '';
	} 
	elseif (is_day()) {
		$capt	= '<h1>'. sprintf( __('Archives: %s', 'gaetheme'), get_the_time( 'M jS, Y' ) ) .'</h1>';
		$desc	= '';
	} 
	elseif (is_month()) {
		$capt	= '<h1>'. sprintf( __('Archives: %s', 'gaetheme'), get_the_time( 'F Y' ) ) .'</h1>';
		$desc	= '';
	} 
	elseif (is_year()) {
		$capt	= '<h1>'. sprintf( __('Archives: %s', 'gaetheme'), get_the_time( 'Y' ) ) .'</h1>';
		$desc	= '';
	} 
	elseif (is_search()) {
		$capt	= '<h1>'. __('Search Results', 'gaetheme') .'</h1>';
		if ($searchcount != 0)
			$desc	= '<p>'. sprintf( __('Search Results for: "%s".', 'gaetheme'), $s) .'</p>';
		else
			$desc	= '<p>'. sprintf( __('No Results for: "%s".', 'gaetheme'), $s) .'</p>';
	} 
	elseif (is_404()) {
		$capt	= '<h1 class="page-title">'. __('Page Not Found') .'</h1>';
		$desc	= '<p>'. __("The page you're looking for is not available. The page may have been deleted or the URL has changed. You can try searching the page with the search form.") .'</p>';
	} 
	else {
		$capt	= '<h1>'. __('Archive Entries', 'gaetheme') .'</h1>';
		$desc	= '';
	} 
	
	return $capt . $desc;
}

function get_caption() {
	echo '<div class="caption">'. gae_theme_caption() .'</div>';
}




/*------------------------------------------------------------------
	- Gae entry title
------------------------------------------------------------------*/

function gae_entry_title() {
	if ( is_singular() ) {
		echo '<h1 class="entry-title">'. get_the_title() .'</h1>';
	} else {
		echo '<h2 class="entry-title"><a href="'. get_permalink() .'" title="'. get_the_title() .'">'. get_the_title() .'</a></h2>';
	}
}




/*------------------------------------------------------------------
	- Gae entry pages
------------------------------------------------------------------*/

function gae_entry_pages() {
	echo wp_link_pages( array('before' => '<p class="entry-nav clearfix"><span>' . __('Pages:', 'gaetheme') .'</span>', 'after' => '</p>', 'echo' => '0' ) );
}




/*------------------------------------------------------------------
	- Gae entry categories
------------------------------------------------------------------*/

function gae_entry_cats($sep = ' ', $title = 'Under') {
	if ( !get_the_category_list() ) return;
	echo '<div class="entry-cats clearfix">'. "\n"
		. '<span>'. $title .'</span> '. get_the_category_list( $sep ) . "\n"
		. '</div>'. "\n";
}




/*------------------------------------------------------------------
	- Gae entry tags
------------------------------------------------------------------*/

function gae_entry_tags($sep = ' ', $title = 'Tagged') {
	if ( !get_the_tag_list() ) return;
	echo '<div class="entry-tags clearfix">'. "\n"
		. '<span>'. $title .'</span> '. get_the_tag_list( '', $sep ) . "\n"
		. '</div>'. "\n";
}




/*------------------------------------------------------------------
	- Gae entry terms
------------------------------------------------------------------*/

function gae_entry_terms($sep = ' ', $title = '') {
	$taxs = get_taxonomies('', 'objects');
	unset($taxs['category'],$taxs['post_tag'],$taxs['post_format'],$taxs['nav_menu'],$taxs['link_category'],$taxs['format']);
	foreach ($taxs as $key=>$tax) {
		echo '<div class="entry-terms clearfix">'. "\n"
			. '<span>'. $tax->labels->name . $title .'</span> '. get_the_term_list(null, $key, '', $sep) . "\n"
			. '</div>'. "\n";
	}
}



/*------------------------------------------------------------------
	- Gae theme copyright
------------------------------------------------------------------*/

function get_copyright() {
	global $wpdb;
	$all_dates = $wpdb->get_results("SELECT YEAR(min(post_date_gmt)) AS firstdate, YEAR(max(post_date_gmt)) AS lastdate FROM $wpdb->posts WHERE post_status = 'publish'");
	if($all_dates) {
		$year = $all_dates[0]->firstdate;
		if($all_dates[0]->firstdate != $all_dates[0]->lastdate) {
			$year .= '-'. $all_dates[0]->lastdate;
		}
		$year = $year;
	}
	return '<p class="copyright">'. sprintf( __('&copy; %1$s %2$s. All rights reserved', 'gaetheme' ), $year, '<a href="'. get_bloginfo('url') .'" title="'. get_bloginfo('description') .'">'. get_bloginfo('name') .'</a>' ) .'</p>';
}




/*------------------------------------------------------------------
	- Gae theme generator
------------------------------------------------------------------*/

function get_generator() {
	$theme_data = theme_data_init();
	return sprintf( __('Powered by %1$s &ndash; Theme %2$s by %3$s', 'gaetheme' ), '<a href="http://wordpress.org/" title="Wordpress '. get_bloginfo('version') .'">Wordpress</a>', '<a href="'. $theme_data['URI'] .'" title="'. str_replace(' Free', '', $theme_data['Name']) .' '. $theme_data['Version'] .'">'. str_replace(' Free', '', $theme_data['Name']) .'</a>', '<a href="'. $theme_data['AuthorURI'] .'" title="'. $theme_data['AuthorName'] .'">'. $theme_data['AuthorName'] .'</a>' );
}




/*------------------------------------------------------------------
	- Gae social_network
------------------------------------------------------------------*/

function gae_social_network( $wrap_open = '<div class="social-network clearfix">', $wrap_close = '</div>', $list_open = '', $list_close = '', $display_title = true ) {
	$wrap_open = !empty($wrap_open) ? $wrap_open : '<div class="social-network clearfix">';
	$wrap_close = !empty($wrap_close) ? $wrap_close : '</div>';
	$content = $wrap_open;
	if ( $display_title ) {
		$content .= $list_open .'<span>' . get_theme_option('social_net_title') . '</span>'. $list_close;
	}
	$accounts = get_theme_option('social_net_accounts');
	foreach ( $accounts as $media=>$account ) {
		$account_url = ( isset($account['url']) ) ? $account['url'] : '';
		$account_name = ( isset($account['name']) ) ? $account['name'] : '';
		if ( !empty($account_url) && !empty($account_name) ) {
			$content .= $list_open .'<a href="'. $account['url'] .'" title="'. $account_name .'"><img src="'. $account['icon'] .'" alt="'. $account_name .'" /></a>'. $list_close;
		}
	}
	$content .= $wrap_close;
	return $content;
}




/*------------------------------------------------------------------
	- Add body classes
------------------------------------------------------------------*/

function gae_body_class($classes) {
	global $is_lynx, $is_gecko, $is_IE, $is_opera, $is_NS4, $is_safari, $is_chrome, $is_iphone;
	
	// OS
	$browser = $_SERVER[ 'HTTP_USER_AGENT' ];
	if ( preg_match( "/Mac/", $browser ) ) $classes[] = 'mac';
	elseif ( preg_match( "/Windows/", $browser ) ) $classes[] = 'windows';
	elseif ( preg_match( "/Linux/", $browser ) ) $classes[] = 'linux';
	else $classes[] = 'unknown-os';
	
	// Browser
	if ($is_lynx) $classes[] = 'lynx';
	elseif ($is_gecko) $classes[] = 'gecko';
	elseif ($is_opera) $classes[] = 'opera';
	elseif ($is_NS4) $classes[] = 'ns4';
	elseif ($is_safari) $classes[] = 'safari';
	elseif ($is_chrome) $classes[] = 'chrome';
	elseif ($is_IE) {
		$classes[] = 'ie';
		if ( preg_match( "/MSIE 6.0/", $browser ) ) {
			$classes[] = 'ie6';
		} elseif ( preg_match( "/MSIE 7.0/", $browser ) ) {
			$classes[] = 'ie7';
		} elseif ( preg_match( "/MSIE 8.0/", $browser ) ) {
			$classes[] = 'ie8';
		} elseif ( preg_match( "/MSIE 9.0/", $browser ) ) {
			$classes[] = 'ie9';
		}
	}
	else $classes[] = 'unknown';
	if ($is_iphone) $classes[] = 'iphone';
	
	// Site Mode
	if ( get_mode_option('status') == 'maintenance' ) $classes[] = 'warning-bar';
	if ( get_mode_option('status') == 'construction' ) $classes[] = 'warning-bar';
	if ( preg_match( "/MSIE 6.0/", $browser ) && get_mode_option('status') == 'active' ) $classes[] = 'warning-bar';

	return $classes;
}
add_filter('body_class','gae_body_class');




/*------------------------------------------------------------------
	- Gae Entries display
------------------------------------------------------------------*/

function gae_entries_display($limit, $order) {
	if ( $order == 'recent' ) $arg = 'post_date';
	elseif ( $order == 'random' ) $arg = 'rand';
	elseif ( $order == 'popular' ) $arg = 'comment_count';
	
	$entries = get_posts( 'ignore_sticky_posts=1&numberposts='. $limit .'&orderby='. $arg .'' );
	$output = '<ul class="gae-list-entries">'. "\n";
	if ($entries) { 
		foreach($entries as $entry) {
		ob_start();
			$output .= '<li>'. "\n";
			$output .= gae_the_post_thumbnail($entry->ID, 'widget-thumbnail');
			$output .= '<a title="'. get_the_title($entry->ID) .'" href="'. get_permalink($entry->ID) .'">'. get_the_title($entry->ID) .'</a>'. "\n";
			$output .= '<small>'. date(get_option('date_format'), strtotime($entry->post_date)) .'</small>';
			$output .= '</li>'. "\n";
		ob_end_flush();
		}
	} else {
		$output .= '<li>'. __('No posts yet.', 'gaetheme') .'</li>'. "\n";
	}
	$output .= '</ul>'. "\n";
	wp_reset_postdata();
	
	return $output;
}




/*------------------------------------------------------------------
	- Gae Comments display
------------------------------------------------------------------*/

function gae_comments_display($limit, $length){
	global $wpdb;
	$request  = "SELECT * FROM $wpdb->comments
				JOIN $wpdb->posts ON ID = comment_post_ID
				WHERE comment_approved = '1' AND post_status = 'publish' AND post_password ='' AND comment_type = ''
				ORDER BY comment_date DESC LIMIT $limit"; 
   	$comments = $wpdb->get_results($request);

	$output = '<ul class="gae-list-comments">'. "\n";
	if ($comments) { 
		foreach ($comments as $comment) { 
			ob_start();
				$commenter = empty($comment->comment_author) ? __('Anonymous', 'gaetheme') : $comment->comment_author;		
				$output .= '<li>'. "\n";
				$output .= get_avatar($comment,$size='40' );
				$output .= '<a href="'. get_permalink( $comment->comment_post_ID ) . '#comment-' . $comment->comment_ID .'">'. $commenter .'</a>: ';
				if ( str_word_count($comment->comment_content) > $length ) {
					$array = explode(" ", strip_tags( $comment->comment_content ));
					array_splice($array, $length);
					$output .=  implode(" ", $array) .' &hellip;';
				} else {
					$output .= $comment->comment_content;
				}
				$output .= '</li>'. "\n";
			ob_end_flush();
			} 
		} else { 
			$output .= '<li>'. __('No comments yet.', 'gaetheme') .'</li>'. "\n";
		}
	$output .= '</ul>'. "\n";
		
	return $output;
}




/*------------------------------------------------------------------
	- Gae RSS Feed
------------------------------------------------------------------*/

function gae_rss_output( $rss, $args = array() ) {
	if ( is_string( $rss ) ) {
		$rss = fetch_feed($rss);
	} elseif ( is_array($rss) && isset($rss['url']) ) {
		$args = $rss;
		$rss = fetch_feed($rss['url']);
	} elseif ( !is_object($rss) ) {
		return;
	}

	$output = '';
	if ( is_wp_error($rss) ) {
		$output .= '<li class="error">' . sprintf( __('<strong>RSS Error</strong>: %s', 'gaetheme'), $rss->get_error_message() ) . '</li>';
	}
	extract( $args, EXTR_SKIP );
	$items = (int) $items;
	if ( $items < 1 || 10 < $items )
		$items = 10;
	$show_date     = (int) $show_date;
	if ( !$rss->get_item_quantity() ) {
		$output .= '<li class="error">' . __('An error has occurred; the feed is probably down. Try again later.', 'gaetheme') . '</li>';
		$rss->__destruct();
		unset($rss);
		return;
	}
	foreach ( $rss->get_items(0, $items) as $item ) {
		$link = $item->get_link();
		while ( stristr($link, 'http') != $link )
			$link = substr($link, 1);
		$link = esc_url(strip_tags($link));
		$title = esc_attr(strip_tags($item->get_title()));
		if ( empty($title) )
			$title = __('Untitled', 'gaetheme');
		$date = '';
		if ( $show_date ) {
			$date = $item->get_date( 'U' );
			if ( $date ) {
				$date = ' <span class="date">' . date_i18n( get_option( 'date_format' ) .' '. get_option( 'time_format' ), $date ) . '</span>';
			}
		}
		if ( $link == '' ) {
			$output .= "<li class='feed'>$title{$date}</li>";
		} else {
			$output .= "<li class='feed'><a href='$link' title='$title'>$title</a>{$date}</li>";
		}
	}
	$rss->__destruct();
	unset($rss);
	return $output;
}




/*------------------------------------------------------------------
	- Gae Twitter Feed
------------------------------------------------------------------*/

function gae_get_tweets( $username, $args = '' ) {
	$defaults = array( 'items' => '5', 'show_time' => 1, 'time_format' => 'ago' );
	$set = wp_parse_args($args, $defaults);
	extract($set, EXTR_SKIP);
	include_once( ABSPATH . WPINC . '/feed.php' );
	$rss = fetch_feed( 'http://twitter.com/statuses/user_timeline/' . $username . '.rss' );

	$output = '';
	if ( is_wp_error($rss) ) {
		$output .= '<li class="error">' . sprintf( __('<strong>RSS Error</strong>: %s', 'gaetheme'), $rss->get_error_message() ) . '</li>';
	}
	$limit = ($set['items'] < 1 || 20 < $set['items']) ? '10' : $set['items'];
	$items = $rss->get_items( 0, $limit );
	if ( $username == '' ) {
		$output .= '<li class="error">'. __('Username not specified', 'gaetheme') .' &hellip;</li>';
	} else {
		if ( empty( $items ) )  {
			$output .= '<li class="error">'. __('No public messages', 'gaetheme') .' &hellip;</li>';
		} else {
			foreach ( $items as $i ) {
				$tweet = substr( strstr( $i->get_description(), ': ' ), 2, strlen( $i->get_description() ) ) .' ';
				$ttime = ( $set['time_format'] == 'ago' ) ? gae_time_ago( $i->get_date() ) : date_i18n( get_option( 'date_format' ) .' '. get_option( 'time_format' ), strtotime($i->get_date()) );
				$output .= '<li class="tweet">'. gae_tweet_link($tweet);
				if ( $set['show_time'] == 1 ) {
					$output .= ' <span class="date">'. $ttime . ' <a href="'. $i->get_permalink() .'" target="_blank">#</a></span>'."\n";
				} else {
					$output .= '<a href="'. $i->get_permalink() .'" target="_blank">&rarr;</a>';
				}
				$output .= '</li>' . "\n";
			}							
		}
	}
	return $output;
}

/*	-- Replace tweets content
------------------------------------------------------------------*/

function gae_tweet_link($twt) {
	$twt = preg_replace("#(^|[\n ])([\w]+?://[\w]+[^ \"\n\r\t< ]*)#", "\\1<a href=\"\\2\" target=\"_blank\">\\2</a>", $twt);
	$twt = preg_replace("#(^|[\n ])((www|ftp)\.[^ \"\t\n\r< ]*)#", "\\1<a href=\"http://\\2\" target=\"_blank\">\\2</a>", $twt);
	$twt = preg_replace("/@(\w+)/", "<a href=\"http://twitter.com/\\1\" target=\"_blank\">@\\1</a>", $twt);
	$twt = preg_replace("/#(\w+)/", "<a href=\"http://search.twitter.com/search?q=\\1\" target=\"_blank\">#\\1</a>", $twt);
	return $twt;
}


/*	-- Replace tweets time
------------------------------------------------------------------*/

function gae_time_ago($time) {
	$date = date_i18n('c', strtotime($time));
	if ( !is_numeric( $date ) ) {
		$time_slices = explode( ':', str_replace( ' ', ':', $date ) );
		$date_slices = explode( '-', str_replace( ' ', '-', $date ) );
		$date = gmmktime( (int)$time_slices[1], (int)$time_slices[2], (int)$time_slices[3], (int)$date_slices[1], (int)$date_slices[2], (int)$date_slices[0] );
	}
	$now = current_time('timestamp',0);
	$since = $now - $date;
	$slices = array(
		array( 60 * 60 * 24 * 365 , __('year','gaetheme'), __('years','gaetheme') ),
		array( 60 * 60 * 24 * 30 , __('month','gaetheme'), __('months','gaetheme') ),
		array( 60 * 60 * 24 * 7, __('week','gaetheme'), __('weeks','gaetheme') ),
		array( 60 * 60 * 24 , __('day','gaetheme'), __('days','gaetheme') ),
		array( 60 * 60 , __('hour','gaetheme'), __('hours','gaetheme') ),
		array( 60 , __('minute','gaetheme'), __('minutes','gaetheme') ),
		array( 1, __('second','gaetheme'), __('seconds','gaetheme') )
	);
	for ( $i = 0, $j = count($slices); $i < $j; $i++) {
		$seconds = $slices[$i][0]; 
		if ( ( $count = floor($since / $seconds) ) != 0 )
			break;
	}
	if ( $count == 1 )
		$output = sprintf( __('about %s ago','gaetheme'), '1 '. $slices[$i][1] );
	else
		$output = sprintf( __('about %s ago','gaetheme'), $count .' '. $slices[$i][2] );
	return $output;
}




/*------------------------------------------------------------------
	- Gae Flickr Feed
------------------------------------------------------------------*/

function gae_get_flickr($userid, $count, $order, $size, $tag = '') {
	if ( empty($userid) && empty($tag) ) return;
	$param = '';
	if ( !empty($userid) && !empty($tag) ) {
		$param .= '&source=user_tag&tag='. str_replace(' ', '+', $tag) .'&user='. $userid;
	} elseif ( !empty($userid) && empty($tag) ) { 
		$param .= '&source=user&user='. $userid;
	} elseif ( empty($userid) && !empty($tag) ) { 
		$param .= '&source=all_tag&tag='. str_replace(' ', '', $tag);
	}
	$target = 'http://www.flickr.com/badge_code_v2.gne?count='. $count .'&display='. $order .'&size='. $size . $param .'';
	return '<div class="flickr-photos size-'. $size .' clearfix"><script type="text/javascript" src="'.$target.'"></script></div>';
}




/*------------------------------------------------------------------
	- Gae Video display
------------------------------------------------------------------*/

function gae_get_video($source, $video, $width = '300', $height = '220') {
	if ( empty($source) && empty($video) ) return;
	if ( $height < 100 ) $height = '100';
	if ( $width < 100 ) $width = '100';
	if ( $source == 'youtube' ) {
		$display = '<object type="application/x-shockwave-flash" data="http://www.youtube.com/v/'.$video.'&hd=1" style="width:'.$width.'px;height:'.$height.'px"><param name="wmode" value="opaque"><param name="movie" value="http://www.youtube.com/v/'.$video.'&hd=1" /></object>';
	}
	if ( $source == 'vimeo' ) {
		$display = '<object width="'.$width.'" height="'.$height.'"><param name="allowfullscreen" value="true" /><param name="wmode" value="opaque"><param name="allowscriptaccess" value="always" /><param name="movie" value="http://vimeo.com/moogaloop.swf?clip_id='.$video.'&amp;server=vimeo.com&amp;show_title=0&amp;show_byline=0&amp;show_portrait=0&amp;color=00ADEF&amp;fullscreen=1" /><embed src="http://vimeo.com/moogaloop.swf?clip_id='.$video.'&amp;server=vimeo.com&amp;show_title=0&amp;show_byline=0&amp;show_portrait=0&amp;color=00ADEF&amp;fullscreen=1" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="'.$width.'" height="'.$height.'" wmode="transparent"></embed></object>';
	}
	return $display;
}




/*------------------------------------------------------------------
	(c) GAETHEME.COM 2012
------------------------------------------------------------------*/

?>